name: Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-push-docker-image:

    name: Build Docker image and push to repositories

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        # relative path to the place where source code with Dockerfile is located
        context: .
        # Note: tags has to be all lower-case
        tags: |
          ebini/tuyapower_exporter:latest
          ebini/tuyapower_exporter:v0.1
          ghcr.io/ebini/tuyapower_exporter:latest
          ghcr.io/ebini/tuyapower_exporter:v0.1
        # build on feature branches, push only on master branch
        push: ${{ github.ref == 'refs/heads/master' }}
        # push: true

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
